version: '3.8'

services:
  database:
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_DB: default
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  back:
    build: ./backend/
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: docker.repos.balad.ir/nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - back

  # Node
